import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contato - Point Network",
  description: "Generated by create next app",
};

import Footer from "@/components/ui/footer/footer";
import { Header } from "@/components/ui/header";
import { HeroContact } from "@/components/ui/hero";

import BlogLastsPosts from "@/components/ui/sections/blog-lasts-posts";

export default function Home() {
  return (
    <>
      <Header />
      <HeroContact />
      {/* <BlogLastsPosts /> */}
      <Footer />
    </>
  );
}
