import React from "react";
import type { Metadata } from "next";
import { HeroSolutions } from "@/components/ui/hero";
import CenteredContent from "@/components/ui/sections/centered-content";

import {
  solutionsControleAcessoPage,
  solutionsMoradoresPage,
} from "@/data/solutions-data";
import MainFeaturesList from "@/components/ui/sections/main-features-list";
import FeaturesBoxes from "@/components/ui/sections/features-boxes";

export const metadata: Metadata = {
  title: "Recursos - Point Network",
  description: "Generated by create next app",
};
const DescriptionHtml = () => (
  <>
    <div
      dangerouslySetInnerHTML={{
        __html: solutionsControleAcessoPage.centeredContent.description || "",
      }}
    />
  </>
);

const SolutionsPageItem = () => {
  return (
    <>
      <HeroSolutions
        title={solutionsControleAcessoPage.title}
        description={solutionsControleAcessoPage.desc}
        url={solutionsControleAcessoPage.productURL}
        accentColor={solutionsControleAcessoPage.accentColor}
        bgColor={solutionsControleAcessoPage.bgColor}
      />
      <main>
        <FeaturesBoxes
          data={solutionsMoradoresPage.featuresBoxes}
          className={"pt-52"}
        />
        <CenteredContent
          title={solutionsMoradoresPage.centeredContent.title}
          description={<DescriptionHtml />}
          video={solutionsMoradoresPage.centeredContent.video}
        />
        <MainFeaturesList features={solutionsMoradoresPage.mainFeatures} />
      </main>
    </>
  );
};

export default SolutionsPageItem;
