import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Quem somos - Point Network",
  description: "Generated by create next app",
};

import { HeroFullWidth } from "@/components/ui/hero";

import BlogLastsPosts from "@/components/ui/sections/blog-lasts-posts";
import FullImage from "@/components/ui/sections/full-image";

export default function Home() {
  return (
    <>
      <HeroFullWidth />
      <FullImage />
      <BlogLastsPosts />
    </>
  );
}
