import React from "react";
import type { Metadata } from "next";
import { HeroSolutions } from "@/components/ui/hero";
import CenteredContent from "@/components/ui/sections/centered-content";

import {
  solutionsMoradoresPage,
  solutionsGestaoFinanceiraPage,
} from "@/data/solutions-data";
import MainFeaturesList from "@/components/ui/sections/main-features-list";
import FeaturesBoxes from "@/components/ui/sections/features-boxes";
import BackgroundFeatures from "@/components/ui/sections/background-features";
import FeaturesVideo from "@/components/ui/sections/features-video";

export const metadata: Metadata = {
  title: "Recursos - Point Network",
  description: "Generated by create next app",
};
const DescriptionHtml = () => (
  <>
    <div
      dangerouslySetInnerHTML={{
        __html: solutionsGestaoFinanceiraPage.centeredContent.description || "",
      }}
    />
  </>
);

const SolutionsPageItem = () => {
  return (
    <>
      <HeroSolutions
        title={solutionsGestaoFinanceiraPage.title}
        description={solutionsGestaoFinanceiraPage.desc}
        url={solutionsGestaoFinanceiraPage.productURL}
        accentColor={solutionsGestaoFinanceiraPage.accentColor}
        bgColor={solutionsGestaoFinanceiraPage.bgColor}
      />
      <main>
        <FeaturesBoxes
          data={solutionsGestaoFinanceiraPage.featuresBoxes}
          className={"pt-52"}
        />
        <BackgroundFeatures />
        <FeaturesVideo data={solutionsGestaoFinanceiraPage.featuresVideo} />
        <CenteredContent
          title={solutionsGestaoFinanceiraPage.centeredContent.title}
          description={<DescriptionHtml />}
          video={solutionsGestaoFinanceiraPage.centeredContent.video}
        />
        <MainFeaturesList features={solutionsMoradoresPage.mainFeatures} />
      </main>
    </>
  );
};

export default SolutionsPageItem;
