import React from "react";
import type { Metadata } from "next";
import { HeroBasic } from "@/components/ui/hero";
import { ResourcesContent } from "@/components/ui/sections/resources-content";

export const metadata: Metadata = {
  title: "Recursos - Point Network",
  description: "Generated by create next app",
};

const Recursos = () => {
  return (
    <>
      <HeroBasic
        title="Recursos"
        description="Sabemos que gestão é coisa séria e não é tarefa fácil. Por isso, criamos conteúdos gratuitos para te ajudar"
      />
      <main className="bg-slate-300 py-16 lg:py-32">
        <ResourcesContent />
      </main>
    </>
  );
};

export default Recursos;
