import React from "react";
import type { Metadata } from "next";
import { HeroSolutions } from "@/components/ui/hero";
import CenteredContent from "@/components/ui/sections/centered-content";

import { solutionsAdministradorasPage } from "@/data/solutions-data";
import MainFeaturesList from "@/components/ui/sections/main-features-list";
import FeaturesBoxes from "@/components/ui/sections/features-boxes";
import GridFeaturesAdm from "@/components/ui/sections/grid-features-adm";
import FeaturesVideo from "@/components/ui/sections/features-video";

export const metadata: Metadata = {
  title: "Recursos - Point Network",
  description: "Generated by create next app",
};
const DescriptionHtml = () => (
  <>
    <div
      dangerouslySetInnerHTML={{
        __html: solutionsAdministradorasPage.centeredContent.description || "",
      }}
    />
  </>
);

const SolutionsPageItem = () => {
  return (
    <>
      <HeroSolutions
        title={solutionsAdministradorasPage.title}
        description={solutionsAdministradorasPage.desc}
        url={solutionsAdministradorasPage.productURL}
        accentColor={solutionsAdministradorasPage.accentColor}
        bgColor={solutionsAdministradorasPage.bgColor}
      />
      <main>
        <GridFeaturesAdm className="pt-52 pb-24" />
        <FeaturesVideo data={solutionsAdministradorasPage.featuresVideo} />
        <CenteredContent
          title={solutionsAdministradorasPage.centeredContent.title}
          description={<DescriptionHtml />}
          video={solutionsAdministradorasPage.centeredContent.video}
        />
        <MainFeaturesList
          features={solutionsAdministradorasPage.mainFeatures}
        />
      </main>
    </>
  );
};

export default SolutionsPageItem;
