import React from "react";
import type { Metadata } from "next";
import { HeroSolutions } from "@/components/ui/hero";
import { ResourcesContent } from "@/components/ui/sections/resources-content";
import CenteredContent from "@/components/ui/sections/centered-content";

import { solutionsAdministradorasPage } from "@/data/solutions-data";
import MainFeaturesList from "@/components/ui/sections/main-features-list";

export const metadata: Metadata = {
  title: "Recursos - Point Network",
  description: "Generated by create next app",
};

const SolutionsPageItem = () => {
  return (
    <>
      <HeroSolutions
        title={solutionsAdministradorasPage.title}
        description={solutionsAdministradorasPage.desc}
        url={solutionsAdministradorasPage.productURL}
        accentColor={solutionsAdministradorasPage.accentColor}
        bgColor={solutionsAdministradorasPage.bgColor}
      />
      <main>
        <ResourcesContent />
        <CenteredContent />
        <MainFeaturesList
          features={solutionsAdministradorasPage.mainFeatures}
        />
      </main>
    </>
  );
};

export default SolutionsPageItem;
